domain: liquidstaking.finance
url: https://liquidstaking.finance/
search_enabled: true
title: "Iqlusion Liquid Staking Working Group"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page-:num/"
collections:
  meeting_notes:
    output: true
    permalink: /meeting-notes/:title
defaults:
  - scope:
      path: ""
      type: "meeting_notes"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      with_other_posts: true
      layout: "post"

exclude:
  - readme.md
  - vendor/bundle
  - home
  - LICENSE.txt
  - README.md
